import './globals.css';
import type { Metadata } from 'next';
import { Nunito } from 'next/font/google';
import { library } from '@fortawesome/fontawesome-svg-core';
import { faEllipsis, faCircle, faCircleXmark } from '@fortawesome/free-solid-svg-icons';
import '@fortawesome/fontawesome-svg-core/styles.css';

library.add(faEllipsis, faCircle, faCircleXmark);

const nunito = Nunito({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={nunito.className}>{children}</body>
    </html>
  )
}
