'use client'
import './globals.css';
import type { Metadata } from 'next';
//import { Nunito } from 'next/font/google';
import { library } from '@fortawesome/fontawesome-svg-core';
import { faEllipsis, faCircleXmark, faPencilSquare } from '@fortawesome/free-solid-svg-icons';
import '@fortawesome/fontawesome-svg-core/styles.css';
import Modal from 'react-modal';
import { useEffect } from 'react';
import { Provider } from 'mobx-react';
import store from './mobx/store';

library.add(faEllipsis, faCircleXmark, faPencilSquare);

//const nunito = Nunito({ subsets: ['latin'] })

Modal.setAppElement('body');

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
  }) {
    useEffect(() => {
      // Clean up the modal element when the component unmounts
      return () => {
        Modal.setAppElement('');
      };
    }, []);
  return (
    <html lang="en">
      <body>
      <Provider store={store}>
          {children}
        </Provider>
      </body>
    </html>
  )
}
